# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

if [[ $(uname) == 'FreeBSD' ]];
then
    alias ls='ls -G'
fi

# some more ls aliases
alias ll='ls -alhF'
alias la='ls -AF'
alias l='ls -CF'

#hadoop
alias dfs='hdfs dfs'

#misc
alias wis='whatis -w "*" | grep'
alias fix_ssh='export SSH_AUTH_SOCK=$(find /tmp/ssh-* -name agent.\* -uid $(id -u) | head -n 1)'
alias snap='python -m snappy -c'
alias unsnap='python -m snappy -d'

#version control
alias svndv='svn diff | vim -R -' #view diffs
alias gitdv='git diff | vim -R -' #view diffs
alias gitst='git status'  
alias gitup='git pull --rebase' #update
alias gitci='git commit -a'  #commit
alias gitbn='git checkout -b' #branch new
alias gitbd='git branch -d'  #branch delete
alias gitbr='git checkout master'  #branch reset
alias gitbs='git checkout master'  #branch switch
alias gitbm='git merge' #branch merge
alias gitbl='git show-branch -a --list' #branch list




#######
# Searchs through files recursively. faster than ack last I tested
# example usage: fif php,py some_function
######
fif ()
{
    FTYPES="$1"
    EXPRESSION="$2"
    OPTIONS="$3"

    if [ -z "$FTYPES" -o -z "$EXPRESSION" ]
    then
        echo "Usage: $0 filetype[,...] expression"
        return 1
    fi
        
    if [ -z "$OPTIONS" ]
    then
        OPTIONS="-Hni"
    fi

    FIND_ARGS=
    for FTYPE in $(echo "$FTYPES" | sed -e 's|,| |g')
    do
        if [ -z "$FIND_ARGS" ]
        then
            FIND_ARGS="-iname *.$FTYPE"
        else
            FIND_ARGS="$FIND_ARGS -o -iname *.$FTYPE"
        fi
    done

    set -f
    find . '(' $FIND_ARGS ')' -exec grep --color "$OPTIONS" -e "$EXPRESSION" '{}' '+'
    set +f
}

#######
# Copy and pastes grep output to jump to the line number in VIM
# Useful with fif
######
vig ()
{
    LOCATION=`echo $1 | awk -F ':' '{print \$2,$1}'`
    vim +$LOCATION
}

from_unixtime() {
    date -d @$1
}

to_unixtime() {
    date -d $1 +%s
}
